<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-14H19A0" failures="1" tests="10" name="personalloan" time="0.36" errors="0" timestamp="25 May 2020 01:27:42 GMT">
  <testcase classname="loanapplication.javaproject.testng2" name="sen" time="0.02"/>
  <testcase classname="loanapplication.javaproject.testng2" name="sen1" time="0.012"/>
  <testcase classname="loanapplication.javaproject.testng1" name="sen12" time="0.022"/>
  <testcase classname="loanapplication.javaproject.testng1" name="sen2" time="0.002"/>
  <testcase classname="loanapplication.javaproject.testng1" name="sen20" time="0.003"/>
  <testcase classname="loanapplication.javaproject.testng1" name="sen20" time="0.003"/>
  <testcase classname="loanapplication.javaproject.testng1" name="sen20" time="0.004"/>
  <testcase classname="loanapplication.javaproject.testng3" name="sen5" time="0.001"/>
  <testcase classname="loanapplication.javaproject.testng3" name="sen9" time="0.012">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at loanapplication.javaproject.testng3.sen9(testng3.java:39)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- sen9 -->
  <testcase classname="loanapplication.javaproject.testng1" name="sen3" time="0.002"/>
</testsuite> <!-- personalloan -->
