<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-14H19A0" failures="0" tests="12" name="loanapplication.javaproject.testng1" time="0.263" errors="2" timestamp="16 Jun 2020 05:23:22 GMT">
  <testcase classname="loanapplication.javaproject.testng1" name="sen20" time="0.046"/>
  <testcase classname="loanapplication.javaproject.testng1" name="sen54" time="0.005"/>
  <testcase classname="loanapplication.javaproject.testng1" name="sen52" time="0.017"/>
  <testcase classname="loanapplication.javaproject.testng1" name="sen55" time="0.007"/>
  <testcase classname="loanapplication.javaproject.testng1" name="sen20" time="0.059"/>
  <testcase classname="loanapplication.javaproject.testng1" name="sen3" time="0.000">
    <error message="Method testng1.sen3()[pri:0, instance:loanapplication.javaproject.testng1@196a42c3] depends on not successfully finished methods" type="java.lang.Throwable">
      <![CDATA[java.lang.Throwable: Method testng1.sen3()[pri:0, instance:loanapplication.javaproject.testng1@196a42c3] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1033)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- sen3 -->
  <testcase classname="loanapplication.javaproject.testng1" name="sen50" time="0.044"/>
  <testcase classname="loanapplication.javaproject.testng1" name="sen53" time="0.006"/>
  <testcase classname="loanapplication.javaproject.testng1" name="sen20" time="0.034"/>
  <testcase classname="loanapplication.javaproject.testng1" name="sen51" time="0.019"/>
  <testcase classname="loanapplication.javaproject.testng1" name="sen12" time="0.000">
    <error message="
Parameter &#039;url&#039; is required by @Test on method sen12 but has not been marked @Optional or defined
in C:\Users\sende\AppData\Local\Temp\testng-eclipse-1393210729\testng-customsuite.xml" type="org.testng.TestNGException">
      <![CDATA[org.testng.TestNGException: 
Parameter 'url' is required by @Test on method sen12 but has not been marked @Optional or defined
in C:\Users\sende\AppData\Local\Temp\testng-eclipse-1393210729\testng-customsuite.xml
	at org.testng.internal.Parameters.createParameters(Parameters.java:154)
	at org.testng.internal.Parameters.createParameters(Parameters.java:361)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:451)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1270)
	at org.testng.internal.Invoker.createParameters(Invoker.java:985)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1075)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- sen12 -->
  <testcase classname="loanapplication.javaproject.testng1" name="sen2" time="0.026"/>
</testsuite> <!-- loanapplication.javaproject.testng1 -->
